name: Get FFmpeg

author: mai@dalaomai.cn

description: nothing

inputs:
  ffmpeg_version:
    description: version
    required: false
    default: "3.0.1"

runs:
  using: "composite"
  steps:
    - run: sudo apt update && sudo apt install nasm -y
      shell: bash
    - run: wget -q https://ffmpeg.org/releases/ffmpeg-${{ ffmpeg_version }}.tar.gz
      shell: bash
    - run: tar -zxf ffmpeg-${{ ffmpeg_version }}.tar.gz
      shell: bash
    - run: cd ./ffmpeg-${{ ffmpeg_version }} && sudo ./configure --enable-gpl --enable-shared --disable-programs --disable-doc --enable-avresample && sudo make -j4 && sudo make install
      shell: bash

 