name: Get FFmpeg

author: mai@dalaomai.cn

description: nothing

inputs:
  ffmpeg_version:
    description: version
    required: false
    default: "3.0.1"

runs:
  using: "composite"
  steps:
    - run: sudo apt update && sudo apt install nasm -y
      shell: bash
    - run: wget -q -P ~ https://ffmpeg.org/releases/ffmpeg-${{ inputs.ffmpeg_version }}.tar.gz 
      shell: bash
    - run: tar -zxf ~/ffmpeg-${{ inputs.ffmpeg_version }}.tar.gz -C ~
      shell: bash
    - run: cd ~/ffmpeg-${{ inputs.ffmpeg_version }} && sudo ./configure --enable-gpl --enable-pic --disable-lzma --disable-bzlib --disable-zlib --disable-programs --disable-doc --enable-avresample && sudo make -j4 && sudo make install
      shell: bash

# ./configure --enable-gpl --enable-pic --disable-bzlib --disable-zlib --disable-programs --disable-doc --enable-avresample

# --enable-version3 --enable-nonfree