name: Get FFmpeg

author: mai@dalaomai.cn

description: nothing

inputs:
  ffmpeg_version:
    description: version
    required: false
    default: "3.0.1"

runs:
  using: "composite"
  steps:
    - run: wget -q https://ffmpeg.org/releases/ffmpeg-3.0.2.tar.gz
      shell: bash
    - run: tar -zxvf ffmpeg-3.0.2.tar.gz
      shell: bash
    - run: cd ffmpeg-3.0.2
      shell: bash
    - run: ll
      shell: bash
    - run: ./configure
      shell: bash
    - run: sudo cp -r lib* /usr/local/include/
      shell: bash
    - run: cd ..
      shell: bash
