name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set nasm
        uses: ilammy/setup-nasm@v1

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.6

      - name: Setup Debug Session
        uses: csexton/debugger-action@master

      - name: Get FFmpeg
        uses: ./.github/actions/ffmpeg-action

      # - name: Build
      #   run: go build .

      - name: Create release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.RELESE_TOEN}}
