name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.6

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: make build
