name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      # - name: Set nasm
      #   uses: ilammy/setup-nasm@v1

      - name: Get FFmpeg
        uses: ./.github/actions/ffmpeg-action

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.6

      - name: Build
        run: go build .
